apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: todo-backend

  template:
    metadata:
      labels:
        app: todo-backend

    spec:
      containers:
        - name: backend
          image: sidd200/todo-backend:latest

          ports:
            - containerPort: 8000
          volumeMounts:
            - name: todo-storage
              mountPath: /data
      
      volumes:
        - name: todo-storage
          persistentVolumeClaim:
            claimName: todo-pvc